# -*- coding: utf-8 -*-
"""열두 단계 낱장. 각 장은 왼쪽 구조 좌표와 가운데 문서 두 벌로 이뤄진다."""
from draw import BLUE, GREEN, GREY, PURPLE, RED, step


def build_steps():
    step(1, "문 앞에서 신원 확인", RED,
         [("분류", ["컴포넌트 아님. 진입 표면"]),
          ("런타임", ["코어 2", "Access and Action"]),
          ("담당", ["정세환"]),
          ("계약", ["Principal", "scope 10종은", "guardrails.yaml 이 정본"])],
         "밖에서 들어온 것  HTTP",
         ["POST /v1/cases",
          "Authorization: Bearer acop_...",
          "",
          '{ "request_id": "req-20260831-0001",',
          '  "customer_id": "1f2e...c04a",',
          '  "message": "어제 주문한 거 취소하고',
          '               환불받고 싶어요",',
          '  "channel": "web" }'],
         ["API 키를 확인하고 case:write 권한을 본다",
          "통과해야 Principal 이 만들어진다"],
         "안에서 쓰는 문서  Principal",
         ["Principal(",
          '  tenant_id = "demo",',
          '  scopes    = {"case:write"},',
          '  key_id    = "key-01" )',
          "",
          "이 tenant_id 가 이후",
          "모든 조회 조건에 붙는다"],
         [("Case 없음", GREY)],
         "cases.py:69 create()   ·   security.py:47 require_scope()",
         "남의 테넌트 주문이 섞이는 것을 여기서부터 막는다. 조건 없는 조회는 그 자체가 보안 결함이다.",
         mark=(1, 5, 6))

    step(2, "같은 요청이 아까 왔었나", RED,
         [("분류", ["컴포넌트. 뺄 수 없다"]),
          ("런타임", ["코어 2", "Access and Action"]),
          ("담당", ["정세환"]),
          ("계약", ["idempotency_key", "action_requests 의", "UNIQUE 제약이 강제"])],
         "재료 네 가지",
         ["tenant_id       = demo",
          "request_id      = req-20260831-0001",
          "action_type     = case.create",
          "business_subject",
          '  = "1f2e...c04a:어제 주문한 거..."',
          "",
          "★요청 ID 만 쓰지 않는다",
          "  업무 대상까지 넣는다"],
         ["넷을 이어붙여 해시를 만든다",
          "그 키로 이미 처리했는지 먼저 찾는다"],
         "멱등성 키와 조회 결과",
         ["idempotency_key",
          "  = a3f1c9...  (sha256)",
          "",
          "action_requests 조회",
          "  없음  → 계속 진행",
          "  있음  → 그때 Case 를 그대로 반환",
          "",
          "이 건은 처음이라 계속 간다"],
         [("Case 없음", GREY)],
         "app/core/idempotency.py:8   ·   cases.py:71~79",
         "고객이 취소 버튼을 두 번 눌러도 Case 가 두 개 생기지 않는다. 같은 요청 10회에 실제 처리는 1회다.",
         mark=(0, 1, 4, 5))

    step(3, "Case 를 만들고 첫 이벤트를 남긴다", BLUE,
         [("분류", ["컴포넌트", "Case lifecycle"]),
          ("런타임", ["코어 1", "Case Runtime"]),
          ("담당", ["최연우"]),
          ("계약", ["transition_case()", "상태를 바꾸는", "유일한 문"])],
         "아직 아무 상태도 없다",
         ["customer_cases   행 없음",
          "case_events      행 없음",
          "",
          "만들 재료",
          "  tenant_id, customer_id",
          "  message (개인정보 지운 것)"],
         ["행을 만들고 created 이벤트를 남긴다",
          "둘이 한 트랜잭션으로 묶인다"],
         "상태가 생겼다",
         ["customer_cases  1행",
          "  status  = classifying",
          "  version = 1",
          "",
          "case_events  1행",
          "  event_type = created",
          "",
          "★new 는 행을 만든 찰나에만 있다"],
         [("new  찰나", GREY), ("classifying  v1", BLUE)],
         "app/core/transition.py:116 transition_case()   ·   domain/events.py TRANSITIONS",
         "전이표가 (new, created) 를 classifying 으로 정해 두었다. case_events 는 고치지 않고 추가만 한다.",
         mark=(1, 2, 5, 7))

    step(4, "의도·이슈·감성을 한 번에 분류", GREEN,
         [("분류", ["모듈  voc", "끄면 이 단계가 없다"]),
          ("런타임", ["모델", "Agent Team 밖의", "분류기"]),
          ("담당", ["송채영"]),
          ("계약", ["Classification", "라벨 4개가 전부", "정해진 목록 안"])],
         "들어가는 것",
         ["개인정보를 지운 문장",
          "",
          '"어제 주문한 거 취소하고',
          ' 환불받고 싶어요.',
          ' 아직 안 왔어요."',
          "",
          "status = classifying"],
         ["라벨 네 개를 한 번에 뽑는다",
          "하나라도 목록 밖이면 실패로 친다"],
         "라벨 네 개",
         ['intent     = "return"',
          'issue_code = "return_fee_or_period"',
          'sentiment  = "negative"',
          'severity   = "medium"',
          "",
          "실패하면 값을 비우고",
          "classification_failed 를 남기고",
          "사람에게 넘긴다"],
         [("classifying  v1", GREY), ("routing  v2", BLUE)],
         "feedback.py:33 INTENTS   ·   :86 classify()   ·   cases.py:84~92",
         '"취소" 라고 썼지만 환불을 원하는 문의라 return 으로 간다. 이 한 단어가 어느 팀이 받을지를 정한다.',
         mark=(0, 5, 6, 7))

    step(5, "어느 팀 일인지 찾는다", BLUE,
         [("분류", ["컴포넌트", "Team Registry"]),
          ("런타임", ["코어 1", "Coordination"]),
          ("담당", ["최연우"]),
          ("계약", ["TeamManifest", "accepted_case_types", "만 본다"])],
         "여섯 팀의 자기소개",
         ["return_refund",
          "  return, refund, exchange",
          "procurement_order_payment",
          "  procurement, order, payment",
          "fulfillment_logistics",
          "  fulfillment, shipping",
          "voc_store_manager      other",
          "catalog_verification   catalog"],
         ["intent=return 을 받는 활성 팀을 찾는다",
          "정확히 하나여야 한다"],
         "팀 하나가 정해졌다",
         ["team = return_refund",
          "",
          "나머지 다섯은 안 받는다",
          "response_generation_review 는",
          "  라우팅 대상이 아니다",
          "",
          "둘이거나 없으면",
          "  routing_failed → 사람에게"],
         [("routing  v2", GREY), ("running  v3", BLUE)],
         "app/core/registry.py:54 resolve()   ·   controller.py:124",
         "Core 는 어떤 팀이 있는지 모른다. 자기소개만 보고 고른다. 그래서 팀을 늘려도 Core 코드가 안 바뀐다.",
         mark=(0, 6, 7))

    step(6, "그 팀의 무슨 기능을 쓸지 고른다", BLUE,
         [("분류", ["컴포넌트", "Team Registry"]),
          ("런타임", ["코어 1", "Coordination"]),
          ("담당", ["최연우"]),
          ("계약", ["TeamManifest", ".capabilities", "목록 순서가", "곧 우선순위"])],
         "그 팀이 할 수 있는 일",
         ["capabilities = [",
          '  "return.check_eligibility",',
          '  "return.request",',
          '  "refund.calculate" ]',
          "",
          'intent = "return"'],
         ["intent 와 같거나 intent 로 시작하는",
          "첫 capability 에서 멈춘다"],
         "부를 기능이 정해졌다",
         ['capability',
          '  = "return.check_eligibility"',
          "",
          '"return." 으로 시작하는',
          "첫 항목이라 여기서 멈췄다",
          "",
          "목록 순서를 바꾸면",
          "동작이 바뀐다"],
         [("running  v3", BLUE)],
         "app/core/registry.py:82 capability_for()   ·   controller.py:68 _capability()",
         "규칙이 단순해서 예측이 된다. 대신 목록 순서가 동작을 정하므로 순서를 함부로 바꾸면 안 된다.",
         mark=(0, 1))

    step(7, "근거를 모아 예산 안으로 자른다", PURPLE,
         [("분류", ["컴포넌트", "Context Broker", "+ 모듈 vector_rag"]),
          ("런타임", ["근거 조합", "코어 1 이 부른다"]),
          ("담당", ["최연우 · 모델 공통"]),
          ("계약", ["ContextPack", "Evidence", "예산은", "guardrails.yaml"])],
         "흩어져 있는 재료",
         ["Case 상태 (지금까지의 이벤트)",
          "정책 문서  pgvector 검색",
          "  지식 범위 = order, return,",
          "             refund, exchange, policy",
          "과거 비슷한 Case",
          "도구로 읽은 사실",
          "",
          "다 넣으면 12,000 토큰을 넘는다"],
         ["섹션별 예산에 맞춰 자른다",
          "넘치면 정해진 순서로 빼고 뺐다고 적는다"],
         "ContextPack  전달 문서",
         ["sections   정책 3,600 · 상태 2,400 ...",
          "evidence   [ 출처가 붙은 근거 ]",
          "degraded   false",
          "omissions  []",
          "",
          "검색이 실패했다면",
          "  degraded  = true",
          "  omissions = [policy_rag]"],
         [("running  v3", BLUE)],
         "controller.py:74 _policy()   ·   :89 build()   ·   app/core/context.py:90",
         "검색이 실패해도 빈 결과를 조용히 쓰지 않는다. 신호 없는 축소는 폴백이고, 그 답은 근거 없이 나간다.",
         mark=(2, 3, 6, 7))

    step(8, "Team 이 판단한다", GREEN,
         [("분류", ["인스턴스", "Agent Team 6 중 1", "return_refund"]),
          ("런타임", ["모델", "TeamExecutorPort", "경유"]),
          ("담당", ["서유현"]),
          ("계약", ["TeamTask 들어감", "TeamResult 나옴", "allowed_tools 밖은", "도구함이 거부"])],
         "TeamTask 와 도구로 읽은 사실",
         ["TeamTask(case_id, capability,",
          "         context_pack, run_id)",
          "",
          "read.order   ORD-0201",
          "             30,000원 · 2개 · 어제",
          "read.return  반품 이력 없음",
          "read.policy  반품 정책 문서"],
         ["다섯 가지를 순서대로 검사한다",
          "하나라도 걸리면 거기서 멈춘다"],
         "TeamResult  전달 문서",
         ["다섯 검사 전부 통과",
          "  어제 주문이라 기간 안 (기본 7일)",
          "",
          "next_action = respond",
          "evidence    = [주문 · 반품이력 · 정책]",
          "proposals   = []",
          "",
          "★실행하지 않는다. 제안까지만"],
         [("running  v3", BLUE)],
         "return_refund.py:79 execute()   ·   :54 _policy_days()   ·   :68 _date()",
         "Team 은 부수효과를 실행하지 않는다. 환불이 맞다고 판단해도 환불하지 않고 제안만 돌려준다.",
         mark=(0, 3, 5, 7))

    step(9, "답변 문장을 만들고 톤을 검토한다", GREEN,
         [("분류", ["인스턴스", "response_generation", "_review"]),
          ("런타임", ["모델"]),
          ("담당", ["송채영"]),
          ("계약", ["TeamResult", "★지금 꺼져 있다", "response_review", ".enabled = false"])],
         "Team 이 돌려준 것",
         ["next_action = respond",
          "evidence    = [...]",
          "",
          "여기서 문장을 다듬을 차례다",
          "",
          "초안 생성 → 사실 대조 → 톤 검토"],
         ["세 가지를 하는 단계인데",
          "선언에서 꺼 두었다"],
         "실제로 나가는 문장",
         ["config/project.yaml",
          "  response_review.enabled = false",
          "",
          "그래서 지금 고객이 받는 것은",
          "Team 이 코드에 적어 둔",
          "고정 문구 그대로다",
          "",
          "켜려면 true 로 바꾸고 재기동"],
         [("running  v3", BLUE)],
         "config/project.yaml:18~20   ·   controller.py:179 _maybe_review()",
         "꺼져 있다는 사실을 숨기지 않는다. 켜져 있다고 착각하면 문장 품질을 잘못 평가하게 된다.",
         mark=(0, 1, 4, 5))

    step(10, "결과를 상태로 반영한다", BLUE,
         [("분류", ["컴포넌트", "Controller", "+ Case lifecycle"]),
          ("런타임", ["코어 1", "Case Runtime"]),
          ("담당", ["최연우"]),
          ("계약", ["transition_case()", "다시 이 문을", "지난다"])],
         "돌려받은 TeamResult",
         ["next_action = respond",
          "answer      = 문장",
          "evidence    = [...]",
          "",
          "status  = running",
          "version = 3"],
         ["respond 이므로 completed 이벤트를 남긴다",
          "답변과 근거가 Case 상태에 함께 저장된다"],
         "종결됐다",
         ["status  = resolved",
          "version = 4",
          "",
          "case_events 4행이 됐다",
          "  created → classified",
          "  → routed → completed",
          "",
          "상태와 이벤트가 한 트랜잭션"],
         [("running  v3", GREY), ("resolved  v4", BLUE)],
         "controller.py:172 _apply_result()   ·   :258 _event_for_result()",
         "답은 나갔는데 기록이 없는 상황이 생기지 않는다. 둘이 같은 트랜잭션 안에 있기 때문이다.",
         mark=(0, 1, 7))

    step(11, "고객이 답을 받는다", RED,
         [("분류", ["진입 표면", "REST · MCP 공용"]),
          ("런타임", ["코어 2", "Access and Action"]),
          ("담당", ["정세환"]),
          ("계약", ["CaseView", "근거를 빼고", "답만 주지 않는다"])],
         "조회 요청",
         ["GET /v1/cases/{case_id}",
          "",
          "본인 Case 인지 확인한다",
          "남의 Case 면 404 다",
          "",
          "(있는데 권한이 없다 가 아니라",
          " 없다 고 답한다)"],
         ["상태와 답변과 근거를 함께 내보낸다"],
         "고객이 받는 전달 문서",
         ['{ "status": "resolved",',
          '  "version": 4,',
          '  "intent": "return",',
          '  "issue_code": "return_fee_or_period",',
          '  "answer": "...반품 요청을',
          '              검토할 수 있습니다.",',
          '  "evidence": [ { "source_type":',
          '      "case_event", "source_id": ... } ] }'],
         [("resolved  v4", BLUE)],
         "cases.py:118 detail()",
         '답변에 근거가 같이 나간다. "왜 그렇게 판단했는지" 를 되짚을 수 있어야 하기 때문이다.',
         mark=(6, 7))

    step(12, "기록이 남는다", GREY,
         [("분류", ["컴포넌트", "DB repository", "append-only"]),
          ("런타임", ["전 담당이", "지나간 자리"]),
          ("담당", ["공통"]),
          ("계약", ["case_events 는", "UPDATE·DELETE", "하지 않는다"])],
         "이 한 건이 지나갔다",
         ["열두 단계를 다 지났다",
          "",
          "지나가며 다섯 표에",
          "흔적을 남겼다",
          "",
          "지금 상태는 이벤트를",
          "순서대로 적용한 결과일 뿐이다"],
         ["각 표에 무엇이 남았나",
          "이벤트만 재생하면 그대로 되짚을 수 있다"],
         "남은 것",
         ["customer_cases    1행  resolved v4",
          "case_events       4행  추가만 됨",
          "action_requests   1행  succeeded",
          "agent_runs        1행  시작과 종료",
          "llm_calls         분류에 쓴 프롬프트",
          "",
          "★case_events 를 고치면",
          "  재생이 깨진다"],
         [("resolved  v4", BLUE)],
         "app/infrastructure/db/migrations/001_schema.sql",
         "감사와 재생이 여기서 나온다. 무엇을 근거로 그렇게 답했는지 나중에 다시 확인할 수 있다.",
         mark=(0, 1, 6, 7))
